/**
 * Public support codes are deliberately opaque, fixed-width identifiers.
 * The first character reserves an error family and the final four digits are
 * a sequence. If a family exceeds 9,999 codes, new codes may use a six-digit
 * sequence without changing existing codes.
 */
export const PUBLIC_ERROR_CODES = {
  validation: "C0001",
  network: "C0002",
  offline: "C0003",
  internal: "C0004",
  authDuplicateEmail: "A0001",
  authLoginFailed: "A0002",
  authRefreshInvalid: "A0003",
  authPasswordMismatch: "A0004",
  authLogoutFailed: "A0005",
  authPasswordResetInvalid: "A0006",
  authPasswordResetUserMissing: "A0007",
  authForbidden: "A0008",
  authPasswordResetRateLimited: "A0009",
  userMissing: "U0001",
  userUpdateFailed: "U0002",
  userWithdrawFailed: "U0003",
  transactionFutureDate: "T0001",
  transactionAmount: "T0002",
  transactionAccountMissing: "T0003",
  transactionCardMissing: "T0004",
  transactionMissing: "T0005",
  transactionQueryInvalid: "T0006",
  transactionCardIncome: "T0007",
  transactionInstallmentOnly: "T0008",
  transactionAlreadyInstallment: "T0009",
  accountDuplicate: "K0001",
  accountMissing: "K0002",
  accountListFailed: "K0003",
  accountBalanceInsufficient: "K0004",
  cardListFailed: "D0001",
  cardMissing: "D0002",
  cardDuplicate: "D0003",
  walletDeleted: "W0001",
  categoryListFailed: "G0001",
  categoryMissing: "G0002",
  categoryDuplicate: "G0003",
  iconDuplicate: "I0001",
  iconMissing: "I0002",
  iconNotRegisterable: "I0003",
  iconInUse: "I0004",
  dashboardFailed: "B0001",
  settingInvalid: "E0001",
  settingSaveFailed: "E0002",
  syncFailed: "Y0001",
  syncConflict: "Y0002",
  syncDuplicate: "Y0003",
  cacheFailed: "L0001",
  statisticsFailed: "P0001",
  statisticsQueryInvalid: "P0002",
  receiptImageRequired: "R0001",
  receiptImageUnsupported: "R0002",
  receiptImageInvalid: "R0003",
  receiptImageTooLarge: "R0004",
  receiptAnalysisFailed: "R0005",
  receiptProviderUnavailable: "R0006",
  receiptTimeout: "R0007",
  receiptTextRequired: "R0008",
  receiptProfileUnsupported: "R0009"
} as const;

const internalToPublicCode: Record<string, string> = {
  VALIDATION_001: PUBLIC_ERROR_CODES.validation,
  AUTH_001: PUBLIC_ERROR_CODES.authDuplicateEmail,
  AUTH_002: PUBLIC_ERROR_CODES.authLoginFailed,
  AUTH_004: PUBLIC_ERROR_CODES.authRefreshInvalid,
  AUTH_005: PUBLIC_ERROR_CODES.authPasswordMismatch,
  AUTH_006: PUBLIC_ERROR_CODES.authLogoutFailed,
  AUTH_007: PUBLIC_ERROR_CODES.authPasswordResetInvalid,
  AUTH_008: PUBLIC_ERROR_CODES.authPasswordResetUserMissing,
  AUTH_009: PUBLIC_ERROR_CODES.authForbidden,
  AUTH_010: PUBLIC_ERROR_CODES.authPasswordResetRateLimited,
  USER_001: PUBLIC_ERROR_CODES.userMissing,
  USER_002: PUBLIC_ERROR_CODES.userUpdateFailed,
  USER_003: PUBLIC_ERROR_CODES.userWithdrawFailed,
  TX_001: PUBLIC_ERROR_CODES.transactionFutureDate,
  TX_002: PUBLIC_ERROR_CODES.transactionAmount,
  TX_003: PUBLIC_ERROR_CODES.transactionAccountMissing,
  TX_004: PUBLIC_ERROR_CODES.transactionCardMissing,
  TX_005: PUBLIC_ERROR_CODES.transactionMissing,
  TX_006: PUBLIC_ERROR_CODES.transactionQueryInvalid,
  TX_007: PUBLIC_ERROR_CODES.transactionCardIncome,
  TX_008: PUBLIC_ERROR_CODES.transactionInstallmentOnly,
  TX_009: PUBLIC_ERROR_CODES.transactionAlreadyInstallment,
  ACCOUNT_001: PUBLIC_ERROR_CODES.accountDuplicate,
  ACCOUNT_002: PUBLIC_ERROR_CODES.accountMissing,
  ACCOUNT_003: PUBLIC_ERROR_CODES.accountListFailed,
  ACCOUNT_004: PUBLIC_ERROR_CODES.accountBalanceInsufficient,
  CARD_001: PUBLIC_ERROR_CODES.cardListFailed,
  CARD_002: PUBLIC_ERROR_CODES.cardMissing,
  CARD_003: PUBLIC_ERROR_CODES.cardDuplicate,
  WALLET_001: PUBLIC_ERROR_CODES.walletDeleted,
  CATEGORY_001: PUBLIC_ERROR_CODES.categoryListFailed,
  CATEGORY_002: PUBLIC_ERROR_CODES.categoryMissing,
  CATEGORY_003: PUBLIC_ERROR_CODES.categoryDuplicate,
  ICON_001: PUBLIC_ERROR_CODES.iconDuplicate,
  ICON_002: PUBLIC_ERROR_CODES.iconMissing,
  ICON_003: PUBLIC_ERROR_CODES.iconNotRegisterable,
  ICON_004: PUBLIC_ERROR_CODES.iconInUse,
  DASHBOARD_002: PUBLIC_ERROR_CODES.dashboardFailed,
  SETTING_001: PUBLIC_ERROR_CODES.settingInvalid,
  SETTING_002: PUBLIC_ERROR_CODES.settingSaveFailed,
  SYNC_001: PUBLIC_ERROR_CODES.syncFailed,
  SYNC_002: PUBLIC_ERROR_CODES.syncConflict,
  SYNC_003: PUBLIC_ERROR_CODES.syncDuplicate,
  CACHE_001: PUBLIC_ERROR_CODES.cacheFailed,
  STAT_001: PUBLIC_ERROR_CODES.statisticsFailed,
  STAT_002: PUBLIC_ERROR_CODES.statisticsQueryInvalid,
  RECEIPT_IMAGE_REQUIRED: PUBLIC_ERROR_CODES.receiptImageRequired,
  RECEIPT_IMAGE_UNSUPPORTED: PUBLIC_ERROR_CODES.receiptImageUnsupported,
  RECEIPT_IMAGE_INVALID: PUBLIC_ERROR_CODES.receiptImageInvalid,
  RECEIPT_IMAGE_TOO_LARGE: PUBLIC_ERROR_CODES.receiptImageTooLarge,
  RECEIPT_ANALYSIS_FAILED: PUBLIC_ERROR_CODES.receiptAnalysisFailed,
  RECEIPT_OCR_PROVIDER_UNAVAILABLE: PUBLIC_ERROR_CODES.receiptProviderUnavailable,
  RECEIPT_OCR_TIMEOUT: PUBLIC_ERROR_CODES.receiptTimeout,
  TEXT_PARSE_TEXT_REQUIRED: PUBLIC_ERROR_CODES.receiptTextRequired,
  TEXT_PARSE_PROFILE_UNSUPPORTED: PUBLIC_ERROR_CODES.receiptProfileUnsupported
};

export function toPublicErrorCode(internalCode?: string): string {
  if (!internalCode) return PUBLIC_ERROR_CODES.internal;
  if (isPublicErrorCode(internalCode)) return internalCode;
  return internalToPublicCode[internalCode] ?? PUBLIC_ERROR_CODES.internal;
}

export function isPublicErrorCode(code: unknown): code is string {
  return typeof code === "string" && /^[A-Z0-9]{5}$/.test(code);
}
