CREATE TABLE "CATEGORY" (
    "category_id" BIGSERIAL NOT NULL,
    "user_id" BIGINT,
    "icon_id" BIGINT NOT NULL,
    "category_name" TEXT NOT NULL,
    "show" BOOLEAN NOT NULL DEFAULT true,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CATEGORY_pkey" PRIMARY KEY ("category_id")
);

CREATE TABLE "CATEGORY_USER_SETTING" (
    "category_user_setting_id" BIGSERIAL NOT NULL,
    "user_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "show" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CATEGORY_USER_SETTING_pkey" PRIMARY KEY ("category_user_setting_id")
);

CREATE UNIQUE INDEX "CATEGORY_default_category_name_key" ON "CATEGORY"("category_name") WHERE "is_default" = true;
CREATE UNIQUE INDEX "CATEGORY_user_id_category_name_key" ON "CATEGORY"("user_id", "category_name");
CREATE INDEX "CATEGORY_user_id_idx" ON "CATEGORY"("user_id");
CREATE INDEX "CATEGORY_icon_id_idx" ON "CATEGORY"("icon_id");
CREATE INDEX "CATEGORY_category_name_idx" ON "CATEGORY"("category_name");
CREATE INDEX "CATEGORY_show_idx" ON "CATEGORY"("show");
CREATE INDEX "CATEGORY_is_default_idx" ON "CATEGORY"("is_default");

CREATE UNIQUE INDEX "CATEGORY_USER_SETTING_user_id_category_id_key" ON "CATEGORY_USER_SETTING"("user_id", "category_id");
CREATE INDEX "CATEGORY_USER_SETTING_user_id_idx" ON "CATEGORY_USER_SETTING"("user_id");
CREATE INDEX "CATEGORY_USER_SETTING_category_id_idx" ON "CATEGORY_USER_SETTING"("category_id");
CREATE INDEX "CATEGORY_USER_SETTING_show_idx" ON "CATEGORY_USER_SETTING"("show");

ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("user_id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CATEGORY" ADD CONSTRAINT "CATEGORY_icon_id_fkey" FOREIGN KEY ("icon_id") REFERENCES "ICON"("icon_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CATEGORY_USER_SETTING" ADD CONSTRAINT "CATEGORY_USER_SETTING_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CATEGORY_USER_SETTING" ADD CONSTRAINT "CATEGORY_USER_SETTING_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "CATEGORY"("category_id") ON DELETE RESTRICT ON UPDATE CASCADE;
